<a href="https://colab.research.google.com/github/jeevan97achar/numpy/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
%cd /content/drive/MyDrive/Github/numpy

/content/drive/MyDrive/Github/numpy


What is NumPy?
* It is multi dimensional arary library.
* Can store all sorts of data in 1d 2d and 3d etc


Why NumPy?
* It is faster than Lists in python

Why is it fast?
1. Fixed type
* Faster to read less bytes of memory
* No type checking when iterating through objects

2.  Contigous Memory
* It uses SIMD Vector Processing
* Effective cache utilization

In [33]:
import numpy as np

# The Basics

In [34]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [39]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[5,6.7,8]])
print(b)

[[9.  8.  7. ]
 [6.  5.  4. ]
 [5.  6.7 8. ]]


In [ ]:
# Getting the dimension
b.ndim

In [38]:
# Getting the shape
b.shape

(2, 3)

In [41]:
# Get Type
a.dtype

dtype('int64')

In [54]:
# We can specify the size an array is supposed to take
a2 = np.array([1,2,3], dtype='int16')

In [55]:
a2.dtype

dtype('int16')

In [56]:
# Get the itemsize
# This tells the number of bytes of an array
a2.itemsize

2

In [57]:
# Get the size
# This gives the number of items in the array
a2.size

3

In [59]:
# Get total size
# This si array.size * array.itemsize
a2.nbytes

6

## Accessing/Changing specific elements, rows, columns, etc

In [62]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [63]:
# Get specific element [r, c]
a[1,5]

13

In [68]:
a[1,-2]

13

In [69]:
# Get specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [70]:
# Get specific column
a[:, 2]

array([ 3, 10])